LICENSE.md, README.md
Adds the copyright notice to `README.md`, and adds a `LICENSE.md` file.
=> Add copyright notice and license

LICENSE.md, README.md, requirements_rtd.txt
Adds a requirements file without `mpi4py` for Read the Docs.
=> Add a requirements file for documentation automation

requirements_rtd.txt
=> Increment programout version

docs/executables.rst, requirements.txt
=> Fix help message renderings for executables

docs/installation.rst, tools/install.sh
=> Change text to boldface

spotlight/gsas.py
=> Add simulate histogram for GSAS wrappers.

requirements.txt
=> Increment matplotlib version required.

spotlight/gsas.py
Prints the output from external calls in ``spotlight.gsas``.
=> Print output of external commands with debug

spotlight/gsas.py
Typecasts a ``map`` as a ``list`` in ``spotlight.gsas``.
=> Typecast map as a list

spotlight/gsas.py, tools/install.sh, tools/install_darwin.sh
Wraps site-specific install script around the core install script.
=> Wrap around core install script

tools/install.sh
Installs SVN in ``install.sh``.
=> Install SVN.

requirements.txt, requirements_rtd.txt
=> Increment numpy version.

docs/installation.rst, examples/lead_sulphate/run_spotlight.sh, requirements.txt, tools/install.sh, tools/install_darwin.sh
This increments the OpenMPI version to a newer stable version.
=> Increment OpenMPI version

docs/installation.rst
Updates the versions of dependencies from changes in #15.
=> Update versions in documentation

bin/gsasii/gsasii_write_csv
Fixes plotting profiles for a specified histogram.
=> Select histogram in GSAS-II write CSV execuable.

.gitignore, docs/installation.rst, setup.py, tools/install.sh, tools/install_minimal.sh
Adds MacOS support for ``tools/install.sh``.
Also updates project URL in ``setup.py`` and adds comments to ``.gitignore``.
=> Support MacOS in install script

spotlight/solver.py
Make it optional to print updates to ``stdout``. Default is set to ``False`` (i.e. do not print).
=> Print updates to stdout is optional

spotlight/io/configuration_file.py, spotlight/sampling.py, spotlight/solver.py
Adds the ``linspace`` sampling method which takes the ``i``-th linearly spaced point from the boundary.
The point is offset by half the step size, so neither edge is selected.
=> Add linspace sampling method

examples/volcano/spotlight_interpolate.py
Since interactivity is not required, then use ``Agg`` to avoid issues.
=> Use Agg backend in interpolation plotting

bin/spotlight_minimize, setup.py, tools/environment.yaml
=> Add an example conda enviornment with spotlight and milk

tools/environment.yaml
Forgot to add the version numbers for MILK dependencies.
=> Add versions for MILK dependencies in example conda env.

examples/volcano/config_analytical.py
Removes functions and just calls them in ``compute``.
=> Simplify Volcano Python file.

examples/volcano/config_analytical.py
=> Remove seed var in Volcano example

examples/volcano/run_spotlight.sh
No longer needed now that tag is defaulted to seed.
=> Remove seed var in run script.

examples/volcano/run_spotlight.sh
Removes this option since its using the default. Make example simplier.
=> Remove tmpdir option.

spotlight/tests/test_gsas.py
Adds one test as an example for more tests.
=> Add a simple test suite example

.readthedocs.yaml
=> Add conda env for doc env.

.readthedocs.yaml
=> Update path to pre-install script

spotlight/sampling.py, spotlight/solver.py, spotlight/tests/scripts/hello_world.py, spotlight/tests/test_scripts.py
Also turn sampling functions into classes.
=> Ad test for arbitrary scripts to test suite

.gitignore, docs/conf.py, docs/index.rst, docs/notebooks/tutorial_mystic.ipynb, spotlight/driver.py, spotlight/tests/scripts/volcano.py, spotlight/tests/test_driver.py, spotlight/tests/test_scripts.py, tools/environment_rietveld.yaml
Adds a basic ``mystic`` tutorial as example using notebook in tutorial.
=> Add notebook example to tutorial

.readthedocs.yaml, docs/conf.py, docs/tutorial_installation.rst, docs/tutorial_introduction.rst, tools/environment_milk.yaml, tools/environment_rietveld.yaml, tools/install_rietveld.sh
Also change env to ``environment_milk.yaml``. The current seesm to be too memory intensive for readthedocs.
=> Update installation instructions.

tools/environment_docs.yaml
For building iPython notebooks with new enviornment.
=> Add ipykernel to docs environment.

examples/lead_sulphate/config_pbso4.py, examples/lead_sulphate/run_spotlight.sh
The ordering now matters for reading the CIF file. Also only look for initial lattice parameters.
This was tested with GSAS-II revision r5609.
=> Move import for GSASIILattice

tools/environment_gsas2.yaml
This adds a GSAS-II environment file.
=> Add GSAS-II environment.
